---
- name: Configure and Update Proxmox Host Node
  hosts: proxmox_nodes
  gather_facts: true

  tasks:
    - name: Ensure the system cache is up to date and packages are upgraded
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Ensure vital host utility utilities are installed
      apt:
        name:
          - curl
          - git
          - htop
          - screen
          - qemu-guest-agent
        state: present
